global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: postgres_content
    static_configs:
      - targets: ["postgres_exporter_content:9187"]

  - job_name: postgres_tester
    static_configs:
      - targets: ["postgres_exporter_tester:9187"]

  - job_name: content_service
    metrics_path: /metrics
    static_configs:
      - targets: ["content_service:8000"]

  - job_name: tester_service
    metrics_path: /metrics
    static_configs:
      - targets: ["tester_service:8001"]

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
